DROP TABLE IF EXISTS CITY;
CREATE TABLE CITY (
City_code INT AUTO_INCREMENT  PRIMARY KEY,
city_name VARCHAR(50) NOT NULL,
city_pincode INT(8) NOT NULL
);


CREATE TABLE IMAGES (
AccessionID VARCHAR(50) PRIMARY KEY NOT NULL,
Author VARCHAR(50) NOT NULL,
Species VARCHAR(50) NOT NULL,
Tissue VARCHAR(50) NOT NULL,
Voxel_Size_Bytes INT(8) NOT NULL,
Dimensions VARCHAR(50)
);

CREATE TABLE IMAGEDIMENSION(
ImageId INT AUTO_INCREMENT  PRIMARY KEY NOT NULL,
Dimension INT(8),
AccessionID VARCHAR (50),
FOREIGN KEY (AccessionID) REFERENCES IMAGES(AccessionID));